import {
    STATION_NAME_MAX_SIZE_IN_BYTES,
    TEMPERATURE_MAX_SIZE_IN_BYTES,
    CHAR_SEMICOLON,
    CHAR_NEWLINE,
} from './constants';

export default {
    STATION_NAME_MAX_SIZE_IN_BYTES,
    TEMPERATURE_MAX_SIZE_IN_BYTES,
    CHAR_SEMICOLON,
    CHAR_NEWLINE,
};
