FROM ubuntu:20.04

ARG WORKDIR=/app/1brc

RUN apt update
RUN apt install openjdk-21-jdk -y
RUN apt install git-all -y

RUN mkdir /app

RUN git clone https://github.com/gunnarmorling/1brc.git $WORKDIR

WORKDIR $WORKDIR

RUN ./mvnw clean verify

CMD ["sh", "-c", "./create_measurements.sh $BRC_NUM_OF_ROWS && mv ./measurements.txt /srv/$host_weather_data_file_name && chmod 777 /srv/$host_weather_data_file_name"]