FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run test
RUN npm run build


FROM node:22-alpine

WORKDIR /app
COPY --from=builder /app/dist /app
CMD ["sh", "-c", "BRC_LOG_LEVEL=$BRC_LOG_LEVEL BRC_DATA_DIR=$BRC_DATA_DIR BRC_FILENAME=$BRC_FILENAME node ./main.js"]